name: bioimage-book
channels:
  - conda-forge
dependencies:
  - python=3.12
  - imageio
  - jupyter-book=1.0.*
  - jupytext
  - matplotlib=3.8.*
  - myst-nb
  - nbclassic=1.3.*
  - numpy=2.3.*
  - pandas=2.3.*
  - scikit-image=0.25.*
  - scipy=1.16.*
  - sphinx-intl=2.3.*
  - sphinx-sitemap=2.7.*
  - pip
  - pip:
    - bioio
    - bioio-tifffile
    - bioio-imageio
