name: deploy-book

# See https://jupyterbook.org/publish/gh-pages.html
# Only run this when the main branch changes
on:
  push:
    branches:
    - main
    # Don't rebuild if we just have changed translation files
    paths-ignore:
    - locales/**
  workflow_dispatch:

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - uses: actions/checkout@v4

    # Install dependencies
    - uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: '3.12'
        mamba-version: "*"
        channels: conda-forge,defaults
        channel-priority: true
        activate-environment: bioimage-book
        environment-file: environment.yml

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build .

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
